baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software Engineer // Tech Lead // Engineering Manager // Event Storming enthusiast"
  homeSubtitleRow2 = "developer [noun] a person who optimizes your business processes with a dash of software"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "developer [noun] a person who optimizes your business processes with a dash of software; I'm your developer, software engineer, tech lead, engineering manager, and event storming enthusiast. Let me help you!"
  keywords = "homepage, blog"
  images = [""]

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/mateuszpawlik/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Mateusz Pawlik"
    subtitle = "Software Engineer // Tech Lead // Engineering Manager // Event Storming enthusiast"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd ~/dev"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"
    identifier = "eventstorming"
    name       = "Event Storming"
    url        = "https://eventstorming.training/"

  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"
    identifier = "poczatkujacyprogramista"
    name       = "Beginner Programmer(pl)"
    url        = "https://poczatkujacyprogramista.pl/"
